apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: config-server
  name: config-server
spec:
  ports:
  - name: 8888-8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  type: ClusterIP
status:
  loadBalancer: {}
