apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-server
    spec:
      containers:
      - image: hlezama/config-server
        name: config-server
        resources: {}
status: {}
