server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:${DB_PORT:3306}/${DB_NAME:reservatio}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:Pass1234}
    driver-class-name: com.mysql.cj.jdbc.Driver