server:
  port: 8081
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:${DB_PORT:3306}/${DB_NAME:reservatio}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:Pass1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    baseUrl: http://host.docker.internal:9411/