apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway-service
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway-service
    spec:
      containers:
        - image: hlezama/gateway-service
          name: gateway-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          ports:
            - containerPort: 8080
          resources: { }
status: { }
