spring:
  application:
    name: host-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"