server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hugolezama/reservatio-spring-microservices
          search-paths: config-data
  application:
    name: config-server